apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-flannel-ds
  namespace: kube-system
  labels:
    app: flannel
spec:
  selector:
    matchLabels:
      app: flannel
  template:
    metadata:
      labels:
        app: flannel
    spec:
      containers:
      - name: kube-flannel
        image: quay.io/coreos/flannel:v0.14.0
        command: [ "/opt/bin/flanneld", "--ip-masq", "--kube-subnet-mgr", "--iface=<INSERT_INTERFACE_NAME_HERE>" ]
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: flannel-cfg
          mountPath: /etc/kube-flannel/
      volumes:
      - name: flannel-cfg
        configMap:
          name: kube-flannel-cfg
  hostNetwork: true
  serviceAccountName: flannel
  tolerations:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule
  - operator: Exists
    effect: NoSchedule
