apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: nginx
    volumeMounts:
    - name: logs
      mountPath: /var/log/myapp
  volumes:
  - name: logs
    emptyDir: {}
